#lang sicp
(define (con-frac n d k)
  (cond ((= k 0) 0)
        (else (/ (n k) (+ (d k) (con-frac n d (- k 1)))))))
(define (ola k)
  (+ 2 (con-frac (lambda (i) 1.0)
                 (lambda (i)
                   (if (= (remainder i 3) 2)
                       (/ (+ i 1) 1.5)
                       1))
                 k)))