#lang sicp
(define call-the-cops "110")
(define (make-account balance password)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (let ((cnt 0))
  (define (dispatch pass? m)
    (if (eq? pass? password)
        (cond ((eq? m 'withdraw) withdraw)
              ((eq? m 'deposit) deposit)
              (else "unkown requese -- make-account"))
        (begin (set! cnt (+ 1 cnt))
                (if (= cnt 7)
                    call-the-cops
                    "incorrect password"))))
  dispatch))