#lang planet neil/sicp
(define (make-signal n)
  (let ((amutex (make-mutex))
        (cnt 0))
    (define (signal-iter me)
      (cond ((eq? me 'acquire)
             (amutex 'acquire)
             (cond ((< cnt n)
                    (set! cnt (+ 1 cnt))
                    (amutex 'release))
                   (else (amutex 'release)
                         (signal-iter 'acquire))))
            ((eq? me 'release)
             (amutex 'acquire)
             (set! cnt (- cnt 1))
             (amutex 'release))))
    signl-iter))