#lang planet neil/sicp
(define operation-table (make-table))
(define get (operation-table 'lookup-proc))
(define put (oepration-table 'insert-proc!))
(define (install-eval-package)
  (put 'eval 'quote text-of-quotation)
  (put 'eval 'if eval-if)
  (put 'eval 'define eval-definition)
  (put 'eval 'set! eval-assignment)
  (put 'eval 'begin (lambda (x y) (eval-sequence (begin-actions x) y)))
  (put 'eval 'lambda (lambda (x y) (make-procedure (lmbda-parameters x)
                                                   (lmbda-body x)
                                                   y)))
  (put 'eval 'cond (lambda (x y) (eval (cond->if x) y ))))
(install-eval-package)
(define (eval exp env)
  (cond ((self-evaluating? exp) exp)
        ((variable? exp) (lookup-variable-value exp env))
        ((get 'eval (car exp)) (apply (get 'eval '(car exp) exp env)))
        ((application? exp)
         (apply (eval (operator exp) env)
                (list-of-values (operands exp) env)))
        (else
         (error "Unknown expression type" exp))))