#lang planet neil/sicp
(define (cons x y)
  (list 'pair (lambda (m) (m x y))))
(define (pair? exp)
  (tagged-list? exp 'pair))
(define (lazy? exp)
  (tagged-list? exp 'lazy))

(define (car z)
  ((cadr z) (lambda (x y) x)))
(define (cdr z)
  ((cadr z) (lambda (x y) y)))
(define (driver-loop)
  (prompt-for-input input-prompt)
  (let ((input (read)))
    (let ((output
           (actual-value input the-global-envirmonet))
          (annouce-output output-prompt)
          (user-print output)))))
(define (user-print object)
  (cond ((compound-procedure? object)
         (display (list 'compound-procedure
                        (procedure-parameters object)
                        (procedure-body object)
                        '<procedure-env>)))
        ((pair? object)
         (display (car object))
         (display "...more element"))
        ((lazy? object)
         (display (list 'lazy (force-it apply (cadr object)
                                        '((lambd (p q) p))
                                        the-global-environment))
                        '..more.element
                        'env))
        (else (display object))))